### ISSUE TITLE
Scale CLI doesn't create preceeding paths for `export` commands

### ISSUE THREAD

**Issue by pojntfx** [loopholelabs/scale-cli#39]
Minor inconvenience I'm noticing with the Scale CLI - unlike say Go, it doesn't create the paths on `export`. For example, I get an error here; coming from Go, I'd probably have expected the output directory to be created:

```shell
scale function export local/questions:latest out
Error: failed to stat output path out: stat out: no such file or directory
```

**Comment by ShivanshVij** [comment]
Fixed in #45
