### ISSUE TITLE
Bug: Allowing dashes (`-`) in function names or signature names breaks Rust 

### ISSUE THREAD

**Issue by ShivanshVij** [loopholelabs/scale-cli#43]

**Comment by dphilla** [comment]
closed: https://github.com/loopholelabs/scale-cli/commit/71e14fb3d0d0075ca36e168d9be668a6a277f49b https://github.com/loopholelabs/scale-cli/commit/6837d43b1eec42a3b10066d2ad8c0445c60788fd
